version: '3.3'
services:
  elastic-node-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: elastic-node-1
    restart: always
    environment:
      - node.name=elastic-node-1
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    # docker limit
    mem_limit: 2048m 
  
    volumes:
      - elastic-data-node1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic-net

volumes:
  elastic-data-node1:
    driver: local

networks:
  elastic-net:
    driver: bridge
